name: Build Linux And Debian
on:
  push:
    paths:
      - '**.cpp'
      - '**.h'
      - '**.o'
      - '**.sln'
      - 'makefile'
      - '**.yml'
      - '*.yml'
jobs:
  build_linux_and_debian:
    name: Build Linux And Debian Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make Linux And Debian
      run: |
        rootpath="$(realpath .)"
        cd ${rootpath}/linux || exit 127
        scripts/prebuild || exit $?
        make releasedynamicall || exit 126
        lspids_linux_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "lspids MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "linux"\n}'
        if ! [[ -d "${rootpath}/docs/json" ]]; then
          mkdir -p .${rootpath}/docs/json
        fi
        if ! [[ -f "${rootpath}/docs/json/lspids_linux_md5.json" ]]; then
          touch "${rootpath}/docs/json/lspids_linux_md5.json"
        fi
        echo -e "$lspids_linux_md5_text" > "${rootpath}/docs/json/lspids_linux_md5.json"
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum ${rootpath}/linux/release/dynamic/lspids | cut -d' ' -f 1)\"/g" "${rootpath}/docs/json/lspids_linux_md5.json"
        cd ${rootpath}/debian || exit 125
        if [[ ! -d "${rootpath}/debian/lspids-1.0.0/usr/bin" ]]; then
          mkdir -p "${rootpath}/debian/lspids-1.0.0/usr/bin" || exit 124
        fi
        cp \
          "${rootpath}/linux/release/dynamic/lspids" \
          "${rootpath}/debian/lspids-1.0.0/usr/bin/lspids" || exit 123
        fakeroot dpkg-deb --build lspids-1.0.0 || exit 122
        lspids_debian_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "lspids-1.0.0.0.deb MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "debian"\n}'
        if ! [[ -f "${rootpath}/docs/json/lspids_debian_md5.json" ]]; then
          touch "${rootpath}/docs/json/lspids_debian_md5.json"
        fi
        echo -e "$lspids_debian_md5_text" > "${rootpath}/docs/json/lspids_debian_md5.json"
        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum ${rootpath}/debian/lspids-1.0.0.deb | cut -d' ' -f 1)\"/g" "${rootpath}/docs/json/lspids_debian_md5.json"
        cd "${rootpath}"
        git add ${rootpath}/docs/json/*
        git config --global user.name 'Lateralus138'
        git config --global user.email 'Lateralus138@users.noreply.github.com'
        git commit --allow-empty -am "Pushed $(printf '%s ' ${rootpath}/docs/json/*) to master. - $(date -u)"
        git push --force origin master
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: 1.0.0
        name: Stable Release
        bodyFile: ./docs/md/release.md
        prerelease: False
        artifacts: ./linux/release/dynamic/lspids,./debian/lspids-1.0.0.deb
        token: ${{ secrets.GITHUB_TOKEN }}
